# Generated by Django 4.2.7 on 2026-01-30 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('roll_number', models.CharField(max_length=50, unique=True, verbose_name='Roll Number/ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('visitor', 'Visitor')], default='student', max_length=20, verbose_name='User Type')),
                ('face_encoding', models.TextField(verbose_name='Face Encoding (JSON)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faces/', verbose_name='Profile Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date')),
            ],
            options={
                'verbose_name': 'Student/Staff',
                'verbose_name_plural': 'Students/Staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('log_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20, verbose_name='Log Type')),
                ('message', models.TextField(verbose_name='Log Message')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time')),
                ('entry_type', models.CharField(choices=[('success', 'Access Granted'), ('denied', 'Access Denied')], default='success', max_length=20, verbose_name='Entry Type')),
                ('location', models.CharField(default='Main Door', max_length=50, verbose_name='Location')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Captured Image Path')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Recognition Confidence')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.student', verbose_name='Student/Staff')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
