# Generated by Django 4.2.7 on 2026-04-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('entry', 'Attendance Entry')], max_length=10, verbose_name='Notification Type')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Linked Object ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('is_cleared', models.BooleanField(default=False, verbose_name='Is Cleared')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_states', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification State',
                'verbose_name_plural': 'Notification States',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'notification_type', 'object_id')},
            },
        ),
        migrations.AddIndex(
            model_name='notificationstate',
            index=models.Index(fields=['user', 'notification_type', 'is_cleared'], name='attendance_n_user_id_8e5d29_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationstate',
            index=models.Index(fields=['user', 'notification_type', 'is_read'], name='attendance_n_user_id_656f29_idx'),
        ),
    ]
