# Generated by Django 5.2.13 on 2026-04-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_entry_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationstate',
            new_name='attendance__user_id_413016_idx',
            old_name='attendance_n_user_id_8e5d29_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationstate',
            new_name='attendance__user_id_511c29_idx',
            old_name='attendance_n_user_id_656f29_idx',
        ),
    ]
